### PR TITLE
Feature landlord execute

### PR DESCRIPTION
**Pull request by masterix21**
Like for the isolated tenant environment, I have built the same feature for the landlord.

Now it's possible to execute landlord-code in a tenant environment:
```php
Landlord::execute(fn () => dispatch(LandlordJob()));
// or
Landlord::execute(fn () => Artisan::call('cache:clear'));
```

### CODE REVIEW

**Comment by freekmurze** [comment]
Nice!

Could you also document this feature?

**Comment by freekmurze** [comment]
Right, I've changed it back, and made that very explicit.

**Comment by masterix21** [comment]
Now, it's great. About the documentation, do you think it is better to extend the "tenant environment" or create a new one?

**Comment by freekmurze** [comment]
Let's extend tenant environment.

**Comment by masterix21** [comment]
Ok! I will asap.

**Comment by masterix21** [comment]
Done

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
