### PR TITLE
Authentication Based Multi-Tenancy

### PR DESCRIPTION
**Pull request by kassah**
This PR adds the middleware required for authentication based multi-tenancy, as well as documentation on how to use it.

#### Example of it's application utilizing the documentation:
https://github.com/kassah/multitenancy-pr-demo

The README in the repository covers demonstration steps.

#### Commit that makes the changes following documentation 
https://github.com/kassah/multitenancy-pr-demo/commit/84d9a80afd8505b9f83b85838b6cb9e661eca929

### Dependency Change
Increased the minimum version of Mockery, so that tests with mocks utilizing shouldNotHaveReceived could function without error.

### Why merge this feature add?
- Inspired by JetStream Teams and the possibility of being able to have a database per team. This is one step in that direction.
- The middleware recreates logic from deeper in this package, to best keep it in sync, I would like to see it apart of the upstream package.

#### Discussions this addresses:
- #389 
- #385 
- #378 
- #334 

#### Laracasts Discussions that seem to match the problem scope this PR is attempting to solve:
- https://laracasts.com/discuss/channels/general-discussion/multi-tenancy-with-multiple-databases
- https://laracasts.com/discuss/channels/general-discussion/app-architecture-feedback-multi-tenancy-multiple-data-centres
- https://laracasts.com/discuss/channels/general-discussion/multi-tenancy-with-separate-databases
- https://laracasts.com/discuss/channels/laravel/dynamic-multi-tenancy-best-practice
- https://laracasts.com/discuss/channels/general-discussion/is-my-application-considered-multi-tenancy

#### Incomplete internet tutorials
- https://mark.fullbrook.me/multi-tenant-databases-with-laravel-jetstream - At the end is specifically missing middleware code. - This is the first web page result when you Google for spatie multiteancy jetstream - https://www.google.com/search?q=Spatie+multitenancy+jetstream

### Requested Feedback
- Should I include more or less documentation? I was trying to strike a balance between showing the use of the middleware and giving them a step by step usage.
- Where would be good places to link to the new documentation. I didn't want to go around changing to much until this feature was overall deemed desirable.
- Middleware is currently reimplementing the same logic from the main `\Spatie\Multitenancy\Multitenancy::determineCurrentTenant` method, I'd love to reuse this method, however it's protected nature makes it inaccessible. Is there a recommended way to make these share code path? I'm especially interested in increasing the long term maintainability of the new middleware.
- The TenantFinder created in the documentation could easily be made into real classes with traits/interfaces for the User model. Is this desirable, or is it better to assume the user will customize this?
- Right now using this causes the TenantFinder to be called twice for each request. Once before routes are defined during the boot process, and later with this middleware. Ideas welcome for ways this can be reduced with configuration in a simple and backwards compatible way?

### Credits

Thanks to @thomasruns for initial research into this subject and @lhartwell for feedback on wording, spelling and grammar with the additional documentation (just the docs addition, not this PR, errors here are my own!)

### Final Comments

Thank you in advance for your consideration. I realize with every feature add, that it must be done carefully and diligently with attention paid to how it will need to be maintained. I hope that by putting this together, it can meet those stringent standards of a feature worth adding.

### CODE REVIEW

**Comment by masterix21** [comment]
@kassah, thanks for your time on it, but IMHO is better to keep all these changes as documentation parts. I don't know if @freekmurze agrees with me, so I prefer him to decide.

**Comment by fuel-wlightning** [comment]
@masterix21 If I can simplify it, living in docs sounds like a good resolution for me. 

Specifically, right now this duplicates the logic in `\Spatie\Multitenancy\Multitenancy::determineCurrentTenant`. If I can figure out a good path making that more accessible, that'd be awesome, and result in simplifying and future proofing the resulting middleware that would appear in documentation.

**Comment by kassah** [comment]
@masterix21 If I can simplify it, living in docs sounds like a good resolution for me.

Specifically, right now this duplicates the logic in \Spatie\Multitenancy\Multitenancy::determineCurrentTenant. If I can figure out a good path making that more accessible, that'd be awesome, and result in simplifying and future proofing the resulting middleware that would appear in documentation.

**Comment by freekmurze** [comment]
I agree with @masterix21 that this would be nice to have in the docs (and not in code in in the interest of keeping the package as simple as it can be)

**Comment by kassah** [comment]
Closed in favor of #399

**Pull request closed without merging**
