### PR TITLE
:cookie: change the failed job database in 'SwitchTenantDatabaseTask'

### LINKED ISSUE #91: when there's a `Failed tenant job` it will be inserted in landlord database
there's two database `for tenant` and `for landlord`

#### Event:
``
public function __construct(TestModel $model)
{
    $this->model = $model;
}
``

#### Listener function:
`
public function handle(TestEvent $event): void
    {
        throw new \Exception("Test record failed jobs");
    }
`

-> database of landlord has failed_jobs table
-> database of tenant has failed_jobs table

### result:
in the tenant failed_jobs table is empty
in the landlord failed_jobs table is:
`
Exception: Test record failed jobs in D:\fullpath\ListenerFile.php:53
Stack trace:
...
`

### PR DESCRIPTION
**Pull request by abderrazzak-oxa**
Fixes #91

### CODE REVIEW

**Comment by masterix21** [comment]
@abderrazzak-oxa, it won't works to who centralize all jobs in the landlord connection also using the `SwitchTenantDatabaseTask`. 

Should be better to create a boolean parameter in the configuration file. Don't you agree with me?

**Comment by abderrazzak-oxa** [comment]
Yes but the `config.queue.failed.database` must be changed when the there's a change from landlord to tenant or vice versa

**Comment by masterix21** [comment]
If I understood your problem, you like to migrate `jobs` and `failed_jobs` in each tenant database. With your changes, if somebody wants to migrate `jobs` and `failed_jobs` in the landlord database, keeping your all jobs tenant-aware, could not.

I think could be better to create a configuration to allow everyone to make their choices, or - better - a `SwitchTenantJobsDatabaseTask`: it will keep fully customizable the package.

**Comment by abderrazzak-oxa** [comment]
or we can do this when the tenant is forgot we can assign the old database connection to failed.database like this:

```
class SwitchTenantDatabaseTask implements SwitchTenantTask
{
    use UsesMultitenancyConfig;

    protected $failedJobDatabaseConnection;

    public function __construct()
    {
        $this->failedJobDatabaseConnection = config('queue.failed.database');
    }

    public function makeCurrent(Tenant $tenant): void
    {
        $this->setTenantConnectionDatabaseName($tenant->getDatabaseName());
    }

    public function forgetCurrent(): void
    {
        $this->setTenantConnectionDatabaseName(null);
    }

    protected function setTenantConnectionDatabaseName(?string $databaseName): void
    {
        $tenantConnectionName = $this->tenantDatabaseConnectionName();

        if ($tenantConnectionName === $this->landlordDatabaseConnectionName()) {
            throw InvalidConfiguration::tenantConnectionIsEmptyOrEqualsToLandlordConnection();
        }

        if (is_null(config("database.connections.{$tenantConnectionName}"))) {
            throw InvalidConfiguration::tenantConnectionDoesNotExist($tenantConnectionName);
        }

        config([
            "database.connections.{$tenantConnectionName}.database" => $databaseName,
            "queue.failed.database" => $databaseName === null ? $this->failedJobDatabaseConnection : $tenantConnectionName
        ]);

        DB::purge($tenantConnectionName);
    }
}
```

are you agree with me?

**Comment by abderrazzak-oxa** [comment]
Yes i think it's best to create `SwitchTenantJobsDatabaseTask`, and anyone can create a new tenant task.

but the tenant should change the job database by default or we can create new task called `SwitchTenantJobsDatabaseTask`

**Comment by masterix21** [comment]
I think you can create `SwitchTenantJobsDatabaseTask`

**Comment by abderrazzak-oxa** [comment]
@masterix21 it's created!

**Comment by masterix21** [comment]
Failed jobs are now ok, but what about the jobs table? Don't you think is better to change `queue.connections.database.connection` also? 

Finally, please add the tests.

**Comment by abderrazzak-oxa** [comment]
i think you can't change the queue connection in laravel, if you want to change the queue connection you need to restart this command: `php artisan queue`.

so if you use database connection in the queue you must use one database connection.

so the jobs table must be in one database, i am using redis and the failed job table is in tenant databases and this task is works fine

**Comment by masterix21** [comment]
Why not running `php artisan tenants:artisan "queue:listen" --tenant=xxx` (for each tenant)? If you have a load balancer it could be useful to who can't use Redis.

**Comment by abderrazzak-oxa** [comment]
Ok so what if there's new tenant how can you execute this command, and when you use `supervisor` in `ubuntu`? 

you need to go to `supervisor` config and add the new command for tenant like: `php artisan tenants:artisan "queue:listen" --tenant=2`

**Comment by masterix21** [comment]
I don't know your setup, but from Laravel Forge (for example), you could use the API to set up your new one "queue:listen". 

Anyway, it's better to wait for @freekmurze's thinks. Honestly, I'd prefer to keep the package clean and without any additional jobs setup, but I'm not the one who decides.

Finally, please remember the tests: without, it's harder that @freekmurze will accept the PR.

**Comment by abderrazzak-oxa** [comment]
Yes i know when you want to start the jobs you must use this command for each tenant `php artisan tenants:artisan "queue:listen" --tenant=$tenantID`

but there's no config in this path: `queue.connections.database.connection` to change the database!

#### queue config is:
```
'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 90,
        ],
```

**Comment by masterix21** [comment]
https://stackoverflow.com/questions/35535920/laravel-5-how-to-configure-the-queue-database-driver-to-connect-to-a-non-default

https://stackoverflow.com/questions/41318374/running-laravel-queue-with-multiple-database

**Comment by abderrazzak-oxa** [comment]
Ok so it's good,

now feel free to decline or accept 

@freekmurze

**Comment by freekmurze** [comment]
@abderrazzak-oxa Thanks for your work on this. Could you add some tests and update the docs? Thanks!

**Comment by abderrazzak-oxa** [comment]
@freekmurze, Yes i will do that.

**Comment by abderrazzak-oxa** [comment]
@freekmurze @masterix21  The test is failed ! why?

**Comment by masterix21** [comment]
```
1) Spatie\Multitenancy\Tasks\SwitchTenantJobsDatabaseTest::when_making_a_tenant_current_the_jobs_will_stored_in_his_database
Failed asserting that false is true.

/home/runner/work/laravel-multitenancy/laravel-multitenancy/tests/Feature/Tasks/SwitchTenantJobsDatabaseTest.php:40
```

**Comment by abderrazzak-oxa** [comment]
Hello @masterix21 ,
please check now the problem i found is when change the config `queue.connections.database.connection`
it can't be reconnect!
so how can we reconnect the queue database,

**Comment by masterix21** [comment]
Do you have the code to catch the problem?

**Comment by abderrazzak-oxa** [comment]
Let me to explain to you,

#### this is the tests
// change tenant and change the queue connection database `queue.connections.database.connection`
// dispatch job
$hasJobs = DB::table('jobs')->exists();
$this->assertTrue($hasJobs);

so this test is failed because the `queue.connections.database.connection` is changed but it's not reconnected,


because the laravel just can connect queue one time when the laravel app is started:

#### vendor\laravel\framework\src\Illuminate\Queue\Connectors\DatabaseConnector.php 
```
/**
     * Establish a queue connection.
     *
     * @param  array  $config
     * @return \Illuminate\Contracts\Queue\Queue
     */
    public function connect(array $config)
    {
        return new DatabaseQueue(
            $this->connections->connection($config['connection'] ?? null),
            $config['table'],
            $config['queue'],
            $config['retry_after'] ?? 60
        );
    }
```

#### and i don't found any way to reconnect the queue when tenant changed

- note: The failed jobs is works fine

**Pull request closed without merging**
