### PR TITLE
Subdomain support without strict type

### PR DESCRIPTION
**Pull request by bhushan**
I have added subdomain finder logic

added missing return types in few places

now i need help in hooking both `DomainTenantFinder` and `SubdomainTenantFinder` in this package @freekmurze 

Let me know things i can improve logic or fix anything.. 

my current idea is .. tenant finder should be like `actions` 

it should first check `subdomain` and if we are not on `landlord domain url` then it should check for `domain`.

```php
  'tenant_finders' => [
      Spatie\Multitenancy\TenantFinder\SubdomainTenantFinder::class,
      Spatie\Multitenancy\TenantFinder\DomainTenantFinder::class
],
```

Let me know what you feel about this idea.

I have used NotFoundHttpException is few places.. in SubdomainTenantFinder

I could not figure out where should it go. I want your opinion on that.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for your work on this, but we're not going to merge it in.

We'd like to keep this package as simple as it can be. We think the current way of handling tenant finders offers enough flexibility for most users.

**Comment by bhushan** [comment]
@freekmurze 

that's Ok.. could you give me idea .. how i can achieve it ?

**Comment by freekmurze** [comment]
I would create a single tenant finder and add all necessary logic in there.

**Comment by bhushan** [comment]
I thing you should close issue as well ..

**Pull request closed without merging**
